# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/production/vault.yml

wordpress_sites:
  projet-contester.fr:
    site_hosts:
      - canonical: projet-contester.fr
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:JulesAel/projet-contester.fr.git # replace with your Git repo URL
    repo_subtree_path: site # relative path to your Bedrock/WP directory in your repo
    branch: master
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: true
